### ISSUE TITLE
ResolutionSetterSwift

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [haoict/haoict.github.io#4]
下面的距离写错了，倒数第二个是14ProMax，倒数第一个是14Pro。

![image](https://user-images.githubusercontent.com/32566723/195373816-19df57ef-898c-42cd-a2ab-ff1c43812960.png)

**Comment by haoict** [comment]
Thank you, fixed in the new version 1.1
https://github.com/haoict/haoict.github.io/blob/master/cydia/ipa/ResolutionSetterSwift/ResolutionSetterSwift-1.1.ipa
